import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { emptyResume, ResumeData } from "@shared/types";
import { useEffect, useState } from "react";
import { Download, FilePlus2, Import, Lightbulb, Plus, Save, Trash2 } from "lucide-react";

const uid = () => Math.random().toString(36).slice(2, 9);
export default function Resume() {
  const draft = trpc.resume.getDraft.useQuery(); const [data, setData] = useState<ResumeData>(emptyResume()); const [templateId, setTemplateId] = useState("classic"); const [bullet, setBullet] = useState(""); const [targetRole, setTargetRole] = useState(""); const [suggestion, setSuggestion] = useState("");
  const save = trpc.resume.saveDraft.useMutation(); const importProfile = trpc.resume.importFromProfile.useMutation({ onSuccess: result => { try { setData(JSON.parse(result.data)); } catch {} draft.refetch(); } }); const suggest = trpc.resume.suggestBullet.useMutation({ onSuccess: result => setSuggestion(result.suggestion) }); const exportPdf = trpc.resume.exportPdf.useMutation({ onSuccess: result => window.open(result.url, "_blank") });
  useEffect(() => { if (draft.data) { setData(draft.data.data); setTemplateId(draft.data.draft?.templateId ?? "classic"); } }, [draft.data]);
  const set = <K extends keyof ResumeData>(key: K, value: ResumeData[K]) => setData(prev => ({ ...prev, [key]: value }));
  const updateContact = (key: keyof ResumeData["contact"], value: string) => setData(prev => ({ ...prev, contact: { ...prev.contact, [key]: value } }));
  const commitBullet = (value: string) => { if (!value.trim()) return; setData(prev => ({ ...prev, experience: prev.experience.map(e => e.bullets.includes(bullet) ? { ...e, bullets: e.bullets.map(b => b === bullet ? value : b) } : e) })); setBullet(""); setSuggestion(""); };
  return <DashboardLayout><div className="mx-auto max-w-7xl space-y-6 py-4"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-medium uppercase tracking-[0.2em] text-cyan-700">Resume maker</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Build a resume that reads clearly to people and parsers.</h1><p className="mt-2 text-muted-foreground">Your draft saves to your account. AI suggestions are reviewable and never replace your writing silently.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setData(emptyResume())}><FilePlus2 className="mr-2 h-4 w-4" />New</Button><Button variant="outline" onClick={() => importProfile.mutate()}><Import className="mr-2 h-4 w-4" />Import profile</Button><Button onClick={() => save.mutate({ data, templateId })}><Save className="mr-2 h-4 w-4" />Save draft</Button><Button onClick={() => exportPdf.mutate({ templateId, data })}><Download className="mr-2 h-4 w-4" />Export PDF</Button></div></div>
    <div className="grid gap-6 xl:grid-cols-[1.25fr_0.75fr]"><div className="space-y-6"><Card><CardHeader><CardTitle>Contact information</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2">{(["name", "email", "phone", "location"] as const).map(key => <div key={key} className="space-y-2"><Label>{key[0].toUpperCase() + key.slice(1)}</Label><Input value={data.contact[key]} onChange={e => updateContact(key, e.target.value)} /></div>)}</CardContent></Card>
      <Card><CardHeader><CardTitle>Professional summary</CardTitle></CardHeader><CardContent><Textarea rows={5} value={data.summary} onChange={e => set("summary", e.target.value)} placeholder="A concise, evidence-based summary of your professional direction." /></CardContent></Card>
      <Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle>Work experience</CardTitle><Button size="sm" variant="outline" onClick={() => set("experience", [...data.experience, { id: uid(), title: "", company: "", startDate: "", endDate: "", bullets: [""] }])}><Plus className="mr-1 h-4 w-4" />Add</Button></CardHeader><CardContent className="space-y-5">{data.experience.map((item, index) => <div key={item.id} className="space-y-3 rounded-2xl border p-4"><div className="grid gap-3 md:grid-cols-2"><Input placeholder="Job title" value={item.title} onChange={e => set("experience", data.experience.map(x => x.id === item.id ? { ...x, title: e.target.value } : x))} /><Input placeholder="Company" value={item.company} onChange={e => set("experience", data.experience.map(x => x.id === item.id ? { ...x, company: e.target.value } : x))} /></div><div className="grid gap-3 md:grid-cols-2"><Input placeholder="Start date" value={item.startDate} onChange={e => set("experience", data.experience.map(x => x.id === item.id ? { ...x, startDate: e.target.value } : x))} /><Input placeholder="End date" value={item.endDate} onChange={e => set("experience", data.experience.map(x => x.id === item.id ? { ...x, endDate: e.target.value } : x))} /></div>{item.bullets.map((value, bulletIndex) => <div key={`${item.id}-${bulletIndex}`} className="flex gap-2"><Input placeholder="Achievement bullet" value={value} onChange={e => set("experience", data.experience.map(x => x.id === item.id ? { ...x, bullets: x.bullets.map((b, i) => i === bulletIndex ? e.target.value : b) } : x))} onFocus={() => setBullet(value)} /><Button size="icon" variant="ghost" onClick={() => { setBullet(value); setTargetRole(item.title); }} title="Use for AI suggestion"><Lightbulb className="h-4 w-4 text-amber-600" /></Button></div>)}<div className="flex justify-between"><Button size="sm" variant="ghost" onClick={() => set("experience", data.experience.map(x => x.id === item.id ? { ...x, bullets: [...x.bullets, ""] } : x))}><Plus className="mr-1 h-4 w-4" />Bullet</Button><Button size="sm" variant="ghost" className="text-destructive" onClick={() => set("experience", data.experience.filter(x => x.id !== item.id))}><Trash2 className="mr-1 h-4 w-4" />Remove</Button></div></div>)}</CardContent></Card>
      <Repeatable title="Education" items={data.education} add={() => set("education", [...data.education, { id: uid(), institution: "", degree: "", startDate: "", endDate: "" }])} remove={id => set("education", data.education.filter(x => x.id !== id))} render={item => <div className="grid gap-3 md:grid-cols-2"><Input placeholder="Institution" value={item.institution} onChange={e => set("education", data.education.map(x => x.id === item.id ? { ...x, institution: e.target.value } : x))} /><Input placeholder="Degree" value={item.degree} onChange={e => set("education", data.education.map(x => x.id === item.id ? { ...x, degree: e.target.value } : x))} /></div>} />
      <Card><CardHeader><CardTitle>Skills</CardTitle></CardHeader><CardContent><Input placeholder="Type skills separated by commas" value={data.skills.join(", ")} onChange={e => set("skills", e.target.value.split(",").map(x => x.trim()).filter(Boolean))} /></CardContent></Card>
      <Repeatable title="Certifications" items={data.certifications} add={() => set("certifications", [...data.certifications, { id: uid(), name: "", issuer: "", date: "" }])} remove={id => set("certifications", data.certifications.filter(x => x.id !== id))} render={item => <div className="grid gap-3 md:grid-cols-3"><Input placeholder="Certification" value={item.name} onChange={e => set("certifications", data.certifications.map(x => x.id === item.id ? { ...x, name: e.target.value } : x))} /><Input placeholder="Issuer" value={item.issuer} onChange={e => set("certifications", data.certifications.map(x => x.id === item.id ? { ...x, issuer: e.target.value } : x))} /><Input placeholder="Date" value={item.date} onChange={e => set("certifications", data.certifications.map(x => x.id === item.id ? { ...x, date: e.target.value } : x))} /></div>} />
      <Repeatable title="Projects" items={data.projects} add={() => set("projects", [...data.projects, { id: uid(), name: "", description: "", link: "" }])} remove={id => set("projects", data.projects.filter(x => x.id !== id))} render={item => <div className="space-y-3"><Input placeholder="Project name" value={item.name} onChange={e => set("projects", data.projects.map(x => x.id === item.id ? { ...x, name: e.target.value } : x))} /><Textarea placeholder="Project description" value={item.description} onChange={e => set("projects", data.projects.map(x => x.id === item.id ? { ...x, description: e.target.value } : x))} /><Input placeholder="Project link" value={item.link} onChange={e => set("projects", data.projects.map(x => x.id === item.id ? { ...x, link: e.target.value } : x))} /></div>} /></div>
      <div className="space-y-6"><Card><CardHeader><CardTitle>ATS template</CardTitle></CardHeader><CardContent className="space-y-3"><Select value={templateId} onValueChange={setTemplateId}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{(draft.data?.templates ?? []).map(template => <SelectItem key={template.id} value={template.id}>{template.name}</SelectItem>)}</SelectContent></Select><p className="text-sm text-muted-foreground">Single-column layouts with selectable text and predictable reading order.</p></CardContent></Card><Card><CardHeader><CardTitle>AI writing assistance</CardTitle></CardHeader><CardContent className="space-y-3"><Input placeholder="Target role" value={targetRole} onChange={e => setTargetRole(e.target.value)} /><Textarea placeholder="Paste an existing bullet to improve" value={bullet} onChange={e => setBullet(e.target.value)} /><Button className="w-full" disabled={!bullet || !targetRole || suggest.isPending} onClick={() => suggest.mutate({ currentText: bullet, targetRole })}><Lightbulb className="mr-2 h-4 w-4" />Suggest improvement</Button>{suggestion && <div className="space-y-3 rounded-2xl bg-amber-50 p-4 text-sm text-amber-950"><p className="font-medium">Review this suggestion</p><p>{suggestion}</p><div className="flex gap-2"><Button size="sm" onClick={() => commitBullet(suggestion)}>Accept</Button><Button size="sm" variant="outline" onClick={() => setBullet(suggestion)}>Edit</Button><Button size="sm" variant="ghost" onClick={() => setSuggestion("")}>Reject</Button></div></div>}</CardContent></Card><Card><CardHeader><CardTitle>Draft status</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">{draft.data?.draft ? `Saved ${new Date(draft.data.draft.updatedAt).toLocaleString()}` : "No saved draft yet."}</p></CardContent></Card></div></div>
  </div></DashboardLayout>;
}

function Repeatable({ title, items, add, remove, render }: { title: string; items: Array<{ id: string }>; add: () => void; remove: (id: string) => void; render: (item: any) => React.ReactNode }) { return <Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle>{title}</CardTitle><Button size="sm" variant="outline" onClick={add}><Plus className="mr-1 h-4 w-4" />Add</Button></CardHeader><CardContent className="space-y-3">{items.map(item => <div key={item.id} className="rounded-2xl border p-4"><div className="space-y-3">{render(item)}</div><Button size="sm" variant="ghost" className="mt-3 text-destructive" onClick={() => remove(item.id)}><Trash2 className="mr-1 h-4 w-4" />Remove</Button></div>)}</CardContent></Card>; }
